### PR TITLE
Add Brandon Pitman as a DAP author

### PR DESCRIPTION
**Pull request by tgeoghegan**
Per consensus of the existing DAP authors and the PPM chairs, this commit adds Brandon Pitman as an author of the Distributed Aggregation Protocol.

### CODE REVIEW

**Comment by tgeoghegan** [comment]
@branlwyd Would you please double check that I've put in your information correctly?

**Comment by chris-wood** [comment]
Oops, Tim's comment crossed the air as I merged.

**Comment by tgeoghegan** [comment]
> Oops, Tim's comment crossed the air as I merged.

🤷🏻 We can make another change to correct errors.

**Comment by branlwyd** [comment]
No worries, y'all got it right.

**Comment by cjpatton** [comment]
We also need to remove him from the contributor's list.

**Pull request merged**
