### PR TITLE
Lock spec to draft-irtf-cfrg-vdaf-00

### PR DESCRIPTION
**Pull request by cjpatton**
The current draft is compatible with vdaf-00, and there will likely be
API-breaking changes in vdaf-01. For planned changes see
https://mailarchive.ietf.org/arch/msg/cfrg/Fvd_m64V9bC4VVJm2Zsuwr441mM/.

### CODE REVIEW

**Comment by cjpatton** [comment]
@divergentdave, done (nice catch).

**Review by tgeoghegan — APPROVED** [review]

**Review by chris-wood — APPROVED** [review]
No objections from me, but we could also just wait until VDAF-01 is out and then pin 🤷

**Comment by cjpatton** [comment]
> No objections from me, but we could also just wait until VDAF-01 is out and then pin 🤷

The big task remaining for VDAF-01 is finishing Poplar1, which likely won't happen for several weeks. I suppose we could cut VDAF-01 w/o Poplar1 and save it for VDAF-02?

**Comment by cjpatton** [comment]
I'm going to merge this now, it'll be easy enough to point to the next draft once we're ready.

**Pull request merged**
